# Generated by Django 3.2 on 2022-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('cancelled', 'cancelled'), ('departed', 'departed')], default='scheduled', max_length=30),
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ManyToManyField(related_name='routes', related_query_name='route', to='travel.Route'),
        ),
    ]
